# Generated by Django 4.2.2 on 2024-03-11 10:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productmaterials',
            options={'verbose_name_plural': 'Product Materials'},
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={'verbose_name_plural': 'Warehouses'},
        ),
        migrations.AlterField(
            model_name='productmaterials',
            name='quantity',
            field=models.FloatField(),
        ),
    ]
