# Generated by Django 4.2.2 on 2024-03-11 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0002_alter_productmaterials_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterials',
            name='quantity',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
