# Generated by Django 4.2.2 on 2024-03-11 10:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_alter_productmaterials_quantity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productmaterials',
            name='quantity',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='warehouse',
            name='remainder',
            field=models.FloatField(),
        ),
    ]
