# Generated by Django 4.2.2 on 2024-03-12 07:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_alter_productmaterials_quantity_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductMaterial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('quantity', models.FloatField()),
                ('material', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_products', to='warehouse.material')),
            ],
        ),
        migrations.AlterModelOptions(
            name='warehouse',
            options={},
        ),
        migrations.RenameField(
            model_name='product',
            old_name='bar_code',
            new_name='barcode',
        ),
        migrations.RemoveField(
            model_name='product',
            name='materials',
        ),
        migrations.DeleteModel(
            name='ProductMaterials',
        ),
        migrations.AddField(
            model_name='productmaterial',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='usage_materials', to='warehouse.product'),
        ),
        migrations.AlterUniqueTogether(
            name='productmaterial',
            unique_together={('product', 'material')},
        ),
    ]
